apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tangodev
  labels:
    app: tangodev
spec:
  selector:
    matchLabels:
      app: tangodev
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: tangodev
        tier: frontend
    spec:
      containers:
      - name: tangodev
        image: gerhardlr/tango_gui:latest
        imagePullPolicy: Never #delete this to ensure image is pulled from network
        command:
          - /dockerstartup/vnc_startup.sh
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_DATABASE
            value: tango
          - name: MYSQL_USER
            value: tango
          - name: MYSQL_PASSWORD
            value: tango
          - name: GET_HOSTS_FROM
            value: dns
          - name: TANGO_HOST
            value: databaseds:10000 
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6901
