apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tangotestds
  labels:
    app: tangotestds
spec:
  selector:
    matchLabels:
      app: tangotestds
      tier: test-harness
  replicas: 1
  template:
    metadata:
      labels:
        app: tangotestds
        tier: test-harness
    spec:
      containers:
      - name: tangotestds
        image: ska-registry.av.it.pt/ska-docker/tango-cpp
        command:
          - /usr/local/bin/wait-for-it.sh
        args:
          - databaseds:10000
          - --timeout=30
          - --strict
          - --
          - /usr/local/bin/TangoTest
          - "test"
          - -ORBendPoint
          - giop:tcp::10000
        imagePullPolicy: Never #delete this to ensure image is pulled from network
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_DATABASE
            value: tango
          - name: MYSQL_USER
            value: tango
          - name: MYSQL_PASSWORD
            value: tango
          - name: GET_HOSTS_FROM
            value: dns
          - name: TANGO_HOST
            value: databaseds:10000 
        ports:
        - containerPort: 10000