apiVersion: v1
kind: Service
metadata:
  name: tangotestds
  labels:
    app: tangotestds
    tier: test-harness
spec:
  ports:
  - port: 10000
    targetPort: 10000
  selector:
    app: tangotestds
    tier: test-harness
